# Generated by Django 2.2.10 on 2020-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PFDInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=225)),
                ('Account', models.CharField(max_length=225)),
                ('descripition', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField()),
                ('subtoatal', models.IntegerField()),
                ('shipping', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
